trainer_module: "easymocap.neuralbody.renderer.render_wrapper.RenderWrapper"
trainer_args:
  renderer_module: "easymocap.neuralbody.renderer.render_base.BaseRenderer"
  renderer_args:
    chunk: 4096
    white_bkgd: False
    use_occupancy: True
    N_samples: 64
    split: train
  loss:
    rgb:
      weight: 1.
      module: "easymocap.neuralbody.renderer.render_loss.LossRGB"
      args:
        norm: "l2"

renderer_module: "easymocap.neuralbody.renderer.render_base.BaseRenderer"
renderer_args:
  chunk: 8192
  white_bkgd: True
  use_occupancy: True
  N_samples: 64
  split: test