module: myeasymocap.stages.basestage.MultiStage
args:
  output: output/detect_triangulate
  at_step:
    detect:
      module: myeasymocap.backbone.yolo.yolo.BaseYOLOv5
      key_from_data: [images, imgnames]
      args:
        model: yolov5m
        name: person
    keypoints2d:
      module: myeasymocap.backbone.hrnet.myhrnet.MyHRNet
      key_from_data: [images, imgnames]
      key_from_previous: [bbox]
      key_keep: []
      args:
        ckpt: data/models/pose_hrnet_w48_384x288.pth
    vis2d:
      module: myeasymocap.io.vis.Vis2D
      skip: False
      key_from_data: [images]
      key_from_previous: [keypoints, bbox]
      args:
        name: vis_keypoints2d
        scale: 0.5
    triangulate:
      module: myeasymocap.operations.triangulate.SimpleTriangulate
      key_from_data: [cameras]
      key_from_previous: [keypoints]
      key_keep: [cameras, imgnames]
      args:
        mode: iterative # [naive, iterative]
    visualize:
      module: myeasymocap.io.vis.Vis3D
      key_from_data: [images, cameras]
      key_from_previous: [keypoints3d] # 用于最后的一起优化
      args:
        scale: 0.5
        mode: center
  at_final:
    smooth:
      module: myeasymocap.operations.smooth.Smooth
      key_from_data: [keypoints3d]
      args:
        window_size: 5
    write:
      module: myeasymocap.io.write.Write
      key_from_data: [keypoints3d]
      args: {}
    make_video:
      module: myeasymocap.io.video.MakeVideo
      args:
        fps: 50
        keep_image: False