module: "easymocap.smplmodel.body_model.SMPLlayer"
args:
  model_path: "data/smplx/smpl"
  model_type: "smpl"
  gender: "neutral"
  device: "cuda"
  regressor_path: "data/smplx/J_regressor_body25.npy"
  use_pose_blending: True
  use_shape_blending: True
  use_lbs: True