module: easymocap.bodymodel.smpl.SMPLModel
args:
  model_path: data/bodymodels/SMPL_python_v.1.1.0/smpl/models/basicmodel_neutral_lbs_10_207_0_v1.1.0.pkl
  device: cuda
  regressor_path: data/smplx/J_regressor_body25.npy
  NUM_SHAPES: 10
  use_pose_blending: True