network_module: easymocap.neuralbody.model.nerf.Nerf
network_args:
  # sample_args:
  #   method: uniform
  #   N_samples: 64
  sample_args:
    method: importance
    N_samples: 64
    N_importance: 32
  D: 8
  W: 256
  dim_pts: 3
  dim_dir: 3
  xyz_res: 10
  view_res: 4
  skips: [4]
  use_viewdirs: True
  use_occupancy: True
  linear_func: Linear
  act_fn: expsoftplus
  init_bias: -2.