parents:
  - config/neuralbody/dataset/neuralbody_soccer.yml

data_demo_args:
  split: demo
  image_args:
    scale: 1
  camera_args:
    method: mean
    H: 1080
    W: 1920
    allstep: 800
    loop: True
  object_args:
    ground:
      args:
        xybounds: [-5, 5]
  demo_args:
    mode: scripts
    stages:
      start:
        frame: [0, 40, 1]
        view: [0, 80, 2]
        object_keys: [ground, human_0, human_1, human_2, human_3, human_4, human_5, ball_0]
      # 2. freeze, zoom in, rotate, zoom out
      zoomin:
        frame: [40, 41, 1]
        view: [80, 81, 1]
        object_keys: [ground, human_0, human_1, human_2, human_3, human_4, human_5, ball_0]
        steps: 60
        effect: zoom
        effect_args:
          scale: [1., 2.]
          cx: [1., 1.]
          cy: [1., 1.]
      rotate:
        frame: [40, 41, 1]
        view: [80, 200, 1]
        object_keys: [ground, human_0, human_1, human_2, human_3, human_4, human_5, ball_0]
        effect: none
        effect_args:
          use_previous_K: True
      zoomout:
        frame: [40, 41, 1]
        view: [200, 201, 1]
        object_keys: [ground, human_0, human_1, human_2, human_3, human_4, human_5, ball_0]
        steps: 60
        effect: zoom
        effect_args:
          scale: [2., 1.]
          cx: [1., 1.]
          cy: [1., 1.]
      # 3. keep one person move
      frozen1:
        frame: [40, 200, 2]
        view: [200, 201, 1]
        object_keys: ["ground_@{'frame': 40}", 'ball_0', "human_3_@{'scale_occ': 0.2}", "human_0_@{'frame': 40}", "human_1_@{'frame': 40}", "human_2_@{'frame': 40}", "human_3_@{'frame': 40}", "human_4_@{'frame': 40}", "human_5_@{'frame': 40}"]
      frozen2:
        frame: [199, 39, -2]
        view: [200, 201, 1]
        object_keys: ["ground_@{'frame': 40}", 'ball_0', "human_3_@{'scale_occ': 0.2}", "human_0_@{'frame': 40}", "human_1_@{'frame': 40}", "human_2_@{'frame': 40}", "human_3_@{'frame': 40}", "human_4_@{'frame': 40}", "human_5_@{'frame': 40}"]
      # end of frozen
      # 4. resume play 25 frame; rotate to keyview 2
      normal:
        frame: [40, 65, 1]
        view: [200, 250, 2]
        object_keys: [ground, human_0, human_1, human_2, human_3, human_4, human_5, ball_0]
      bullet:
        frame: [65, 66, 1]
        view: [250, 490, 1]
        object_keys: [ground, human_0, human_1, human_2, human_3, human_4, human_5, ball_0]
      # 5. zoom in , vanish
      zoomin2:
        frame: [65, 66, 1]
        view: [490, 491, 1]
        object_keys: [ground, human_0, human_1, human_2, human_3, human_4, human_5, ball_0]
        steps: 60
        effect: zoom
        effect_args:
          scale: [1., 1.5]
          cx: [1., 0.7]
          cy: [1., 1.]
      # disappear
      disappear3:
        frame: [65, 200, 1]
        view: [490, 491, 1]
        object_keys: [ground, human_0, human_1, human_2, human_3, human_4, human_5, ball_0]
        effect: disappear
        effect_args:
          key: ['human_1', 'human_2', 'human_5']
          use_previous_K: True